### ISSUE TITLE
Use Delta E norm

### ISSUE THREAD

**Issue by ylecuyer** [gausie/colour-proximity#1]
Euclidian distance does not works well inside RGB space. Better, you have to switch to Lab space if you want to use it: http://en.wikipedia.org/wiki/Color_difference

![Delta E norm inside Lab space](http://upload.wikimedia.org/math/9/1/0/910227e12a98c6df4664034d33c2e91c.png)

**Comment by ylecuyer** [comment]
In order to convert RGB to Lab you have to convert RGB to XYZ and then XYZ to Lab.

RGB to XYZ: http://www.brucelindbloom.com/index.html?Eqn_RGB_to_XYZ.html
XYZ to Lab: http://www.brucelindbloom.com/index.html?Eqn_XYZ_to_Lab.html

**Comment by gausie** [comment]
Will give this a go

**Comment by gausie** [comment]
Have updated the package to do exactly this. Thanks for the suggestion!
